### ISSUE TITLE
Dissector output structure includes duplicate keys

### ISSUE THREAD

**Issue by twpayne** [opendroneid/wireshark-dissector#11]
You can export dissector output as JSON in Wireshark. Select a packet (or packets) from your capture, then choose File / Export Packet Dissections / As JSON...

The objects in the resulting JSON file corresponding to opendroneid/wireshark-dissector look like this:

```json
        "opendroneid": {
          "OpenDroneID.counter": "158",
          "opendroneid": {
            "OpenDroneID.msgType": "15",
            "OpenDroneID.protoVersion": "2",
            "OpenDroneID.msgPack_msgSize": "25",
            "OpenDroneID.msgPack_msgQty": "5",
            "opendroneid": {
              "OpenDroneID.msgType": "0",
              "OpenDroneID.protoVersion": "2",
              "OpenDroneID.basicID_idType": "1",
              "OpenDroneID.basicID_uaType": "2",
              "OpenDroneID.basicID_id_asc": "1710FFLATMUAVW000092",
              "OpenDroneID.basicID_reserved": "00:00:00"
            },
            "opendroneid": {
              "OpenDroneID.msgType": "1",
              "OpenDroneID.protoVersion": "2",
              "OpenDroneID.loc_status": "1",
              "OpenDroneID.loc_flag_heightType": "0",
              "OpenDroneID.loc_flag_ewDirectionSegment": "0",
              "OpenDroneID.loc_flag_speedMultiplier": "0",
              "OpenDroneID.loc_direction": "0",
              "OpenDroneID.loc_speed": "0",
              "OpenDroneID.loc_vspeed": "126",
              "OpenDroneID.loc_lat": "471797946",
              "OpenDroneID.loc_lon": "85279560",
              "OpenDroneID.loc_pressAlt": "2893",
              "OpenDroneID.loc_geoAlt": "2963",
              "OpenDroneID.loc_height": "1998",
              "OpenDroneID.loc_hAccuracy": "0",
              "OpenDroneID.loc_vAccuracy": "0",
              "OpenDroneID.loc_baroAccuracy": "0",
              "OpenDroneID.loc_speedAccuracy": "0",
              "OpenDroneID.loc_timeStamp": "25400",
              "OpenDroneID.loc_tsReserved": "0",
              "OpenDroneID.loc_tsAccuracy": "2",
              "OpenDroneID.loc_reserved": "00"
            },
            "opendroneid": {
              "OpenDroneID.msgType": "3",
              "OpenDroneID.protoVersion": "2",
              "OpenDroneID.self_type": "0",
              "OpenDroneID.self_desc": ""
            },
            "opendroneid": {
              "OpenDroneID.msgType": "4",
              "OpenDroneID.protoVersion": "2",
              "OpenDroneID.system_flag_class": "0",
              "OpenDroneID.system_flag_locType": "0",
              "OpenDroneID.system_lat": "471798116",
              "OpenDroneID.system_lon": "85279646",
              "OpenDroneID.system_areaCount": "1",
              "OpenDroneID.system_areaRadius": "0",
              "OpenDroneID.system_areaCeiling": "0",
              "OpenDroneID.system_areaFloor": "0",
              "OpenDroneID.system_usClass": "0x00",
              "OpenDroneID.system_opGeoAlt": "0",
              "OpenDroneID.system_timeStamp": "0",
              "OpenDroneID.system_reserved": "00"
            },
            "opendroneid": {
              "OpenDroneID.msgType": "5",
              "OpenDroneID.protoVersion": "2",
              "OpenDroneID.operator_type": "0",
              "OpenDroneID.operator_id": "",
              "OpenDroneID.operator_reserved": "00:00:00"
            }
          }
        }
```

Notice that the second-level nested `opendroneid.opendroneid` object contains six keys all called `opendroneid`, i.e. the JSON output contains duplicate keys.

Duplicate keys are not mentioned in the JSON specification, and, as a result different decoders handle them in different ways. For example, some (like jq) only use the first value. Others might only use the last value, or attempt some kind of merge.

It would be better if the duplicate keys were renamed to avoid duplicates,for example to `opendroneid.basic_id`, `opendroneid.location`, `opendroneid.auth`, `opendroneid.self_id`, and `opendroneid.operator_id`.

**Comment by gabrielcox** [comment]
@twpayne , I know this has been open for a long time.  I finally tackled it and it should be resolved in the most recent version.  Please close the issue if you agree.

Here's the sample output:


      "opendroneid": {
          "OpenDroneID.counter": "205",
          "opendroneid.message.pack": {
            "OpenDroneID.msgType": "15",
            "OpenDroneID.protoVersion": "0",
            "OpenDroneID.msgPack_msgSize": "25",
            "OpenDroneID.msgPack_msgQty": "5",
            "opendroneid.message.basicid": {
              "OpenDroneID.msgType": "0",
              "OpenDroneID.protoVersion": "0",
              "OpenDroneID.basicID_idType": "1",
              "OpenDroneID.basicID_uaType": "2",
              "OpenDroneID.basicID_id_asc": "SSEVTFG93700070",
              "OpenDroneID.basicID_reserved": "00:00:00"
            },
            "opendroneid.message.location": {
              "OpenDroneID.msgType": "1",
              "OpenDroneID.protoVersion": "0",
              "OpenDroneID.loc_status": "2",
              "OpenDroneID.loc_flag_heightType": "0",
              "OpenDroneID.loc_flag_ewDirectionSegment": "1",
              "OpenDroneID.loc_flag_speedMultiplier": "1",
              "OpenDroneID.loc_direction": "181",
              "OpenDroneID.loc_speed": "255",
              "OpenDroneID.loc_vspeed": "126",
              "OpenDroneID.loc_lat": "0",
              "OpenDroneID.loc_lon": "0",
              "OpenDroneID.loc_pressAlt": "2248",
              "OpenDroneID.loc_geoAlt": "0",
              "OpenDroneID.loc_height": "1999",
              "OpenDroneID.loc_hAccuracy": "0",
              "OpenDroneID.loc_vAccuracy": "0",
              "OpenDroneID.loc_baroAccuracy": "5",
              "OpenDroneID.loc_speedAccuracy": "0",
              "OpenDroneID.loc_timeStamp": "0",
              "OpenDroneID.loc_tsReserved": "0",
              "OpenDroneID.loc_tsAccuracy": "1",
              "OpenDroneID.loc_reserved": "00"
            },
            "opendroneid.message.selfid": {
              "OpenDroneID.msgType": "3",
              "OpenDroneID.protoVersion": "0",
              "OpenDroneID.self_type": "0",
              "OpenDroneID.self_desc": "Drone ID demo"
            },
            "opendroneid.message.system": {
              "OpenDroneID.msgType": "4",
              "OpenDroneID.protoVersion": "0",
              "OpenDroneID.system_flag_class": "1",
              "OpenDroneID.system_flag_locType": "0",
              "OpenDroneID.system_lat": "0",
              "OpenDroneID.system_lon": "0",
              "OpenDroneID.system_areaCount": "1",
              "OpenDroneID.system_areaRadius": "0",
              "OpenDroneID.system_areaCeiling": "0",
              "OpenDroneID.system_areaFloor": "0",
              "OpenDroneID.system_usClassEUCat": "1",
              "OpenDroneID.system_usClassEUCat": "1",
              "OpenDroneID.system_opGeoAlt": "0",
              "OpenDroneID.system_timeStamp": "0",
              "OpenDroneID.system_reserved": "00"
            },
            "opendroneid.message.operatorid": {
              "OpenDroneID.msgType": "5",
              "OpenDroneID.protoVersion": "0",
              "OpenDroneID.operator_type": "0",
              "OpenDroneID.operator_id": "FIN87astrdge12kxyz8",
              "OpenDroneID.operator_reserved": "00:00:00"
            }
          }
        }

**Comment by twpayne** [comment]
This is perfect, thank you very much!
