### ISSUE TITLE
Unable to decode OPENDRONEID protocol

### ISSUE THREAD

**Issue by dakejahl** [opendroneid/wireshark-dissector#13]
@gabrielcox thanks for this work. I am also using the nRF52840 USB dongle but am having the same issue as reported in #12. Can you provide more details on your test setup? I am using the latest [nRF sniffer firmware](https://www.nordicsemi.com/Products/Development-tools/nrf-sniffer-for-bluetooth-le/download#infotabs) (4.1.1) and testing with the [transmitter-linux example](https://github.com/opendroneid/transmitter-linux)
```
sudo ./transmit 5 p
```
In my case I am not seeing BT4 or BT5 packets being decoded. I turned on debug mode in the lua script and am only seeing an error about the packet length being too short. I am using [this network card](https://www.amazon.com/Intel-Wi-Fi-Gig-Desktop-AX200-NGWG-NV/dp/B085M7VPDP/ref=sr_1_1?crid=1J8Q2ER4DFOLM&keywords=intel+2230+wifi&qid=1702586433&sprefix=intel+2230+wifi%2Caps%2C115&sr=8-1) connected to a Jetson Orin Nano running ubuntu 20.04 on the transmitter side and running wireshark 3.6.2 on ubuntu 22.04 on the sniffer side. I am also running wireshark as root.

```
...
debug on
too short
debug on
too short
debug on
too short
...
```
Any help is much appreciated!

**screenshots**
nordic protocol enabled
![image](https://github.com/opendroneid/wireshark-dissector/assets/37091262/bee02ece-fb64-41c1-8a32-1eb49d642c70)

frame data -- I notice S=2, shouldn't it be S=8?
![image](https://github.com/opendroneid/wireshark-dissector/assets/37091262/bf90865b-6128-48e3-b015-096296ceda75)

app output
![image](https://github.com/opendroneid/wireshark-dissector/assets/37091262/8ab181f9-e8eb-4461-8eb8-9d3206251a8b)

**Comment by gabrielcox** [comment]
Your selection on the following screen will be important:
![image](https://github.com/opendroneid/wireshark-dissector/assets/13051211/11d6e403-02c7-4f05-a0c0-75621bd59402)
Selecting the bottom 2 options should bring in the data frames as well as the pointer frames.  The data frames contain the OpenDroneID data.

**Comment by gabrielcox** [comment]
@dakejahl , If you are sending BT5 (LE Coded PHY) frames, which appears to be so, please see my latest instructions.  Basically, the last option ("Scan and follow devices...") needs to be checked (only).  
If this is successful for you, please close with a comment on what worked for you :-).

**Comment by dakejahl** [comment]
I verified the correct boxes are selected for BT4 and BT5 but still no luck. The packet length is still only 34 bytes. I'll try downgrading the sniffer firmware, I see the extended advertising header is labeled as non-connectable and the sniffer 4.1.1 [release notes](https://www.nordicsemi.com/Products/Development-tools/nrf-sniffer-for-bluetooth-le/download#infotabs) mentions a fix around that. Do you know what version of sniffer firmware you are using on the nrf52840 dongle?
![image](https://github.com/opendroneid/wireshark-dissector/assets/37091262/d43c2d3b-10a7-406a-b00e-92d8fe835c28)

**Comment by gabrielcox** [comment]
I'm using 4.1.1 of the sniffer firmware and 4.1.1 of the wireshark plugin.  It's picking it up just fine.  However, I did give you improper instructions, you need to select *both* of the bottom options "Find auxillary pointer data" *and* "Scan and follow devices on LE Coded PHY".  This is for BT5 LE Coded PHY (aka Long Range).  For BT4 Legacy, you only select "Only legacy advertising packets".  I recommend sticking with 4.1.1.

![image](https://github.com/opendroneid/wireshark-dissector/assets/13051211/3c6ffd49-e0bf-4906-bdb9-db7e843863b6)
![image](https://github.com/opendroneid/wireshark-dissector/assets/13051211/d4fcb84f-0f9a-4c35-be13-f2dbe5e2e606)

**Comment by dakejahl** [comment]
Still no luck even with the correct settings. Might try updating my wireshark to 4.0.10

The output of `btmon` suggests it's successfully transmitting 238 bytes (0xea) but wireshark only shows the 34 length
```
< HCI Command:... (0x08|0x0037) plen 238  #29 [hci0] 17.903872
        Handle: 0x01
        Operation: Complete extended advertising data (0x03)
        Fragment preference: Minimize fragmentation (0x01)
        Data length: 0xea
        Service Data (UUID 0xfffa): 0d03f2190902123131323632343135304139304533414531454330000000024246443334353442373738453536354332344237300000001226b500005816af1e38cdffff9808ac0870084a63150e01002210023f003fab0131323334353637383930313233343536372211313233343536373839303132333435363738393031323322123132333435363738393031323334353637383930313233320044726f6e65204944207465737420666c696768742d2d2d420410270000f0d8ffff010000d007d00712f907d51cac0100520046494e38376173747264676531326b3800000000ac0100
> HCI Event: Command Com.. (0x0e) plen 4  #30 [hci0] 17.906285
      LE Set Extended Advertising Data (0x08|0x0037) ncmd 2
        Status: Success (0x00)

```
![image](https://github.com/opendroneid/wireshark-dissector/assets/37091262/f1665ab1-2044-4bc3-9445-754f3e64da9d)

**Comment by gabrielcox** [comment]
I would definitely try upgrading to that version -- that's the one I'm on (4.0.10).  There's probably a good chance that when Nordic puts out their plugin, they focus and integrating with the latest Wireshark version only (as of the time of their distribution).  Also, if you're on linux, have you tried sudoing wireshark to see if it made a difference?

The packets you see there are fine -- they're the "pointer frames" and they are supposed to be 34 bytes.  You'll see those same ones in my screencap.  It's just that it doesn't seem to be following the pointer (which is what that last checkbox on the setup screen is for).

**Comment by NYGTEK** [comment]
can you show your btmon output?

**Comment by NYGTEK** [comment]
I think you haven't open sniffer option: Find auxiliary pointer data.

**Comment by JMoore5353** [comment]
@dakejahl I was having the same issues as you... I added the Fix #14 by NYGTEK to the wireshark dissector and I was able to see the OPENDRONEID information in my packets.

**Comment by gabrielcox** [comment]
Thank you for the contribution @NYGTEK , and thank you for testing as well @JMoore5353 .  This is very helpful. 

I have merged the PR to main.

**Comment by NYGTEK** [comment]
> Thank you for the contribution @NYGTEK , and thank you for testing as well @JMoore5353 . This is very helpful.
> 
> I have merged the PR to main.

Thank your work for this.

**Comment by dakejahl** [comment]
> can you show your btmon output?

Here is the output of btmon running on the transmitter side (Jetson orin nano running ubuntu 20.04)
```
> HCI Event: Command Complete (0x0e) plen 4  #22 [hci0] 7.065468
      LE Set Extended Advertising Enable (0x08|0x0039) ncmd 2
        Status: Success (0x00)
< HCI Command: LE... (0x08|0x0037) plen 238  #23 [hci0] 7.065512
        Handle: 0x01
        Operation: Complete extended advertising data (0x03)
        Fragment preference: Minimize fragmentation (0x01)
        Data length: 0xea
        Service Data (UUID 0xfffa): 0d00f2190902123131323632343135304139304533414531454330000000024246443334353442373738453536354332344237300000001226b500005816af1e38cdffff9808ac0870084a63150e01002210023f003fab0131323334353637383930313233343536372211313233343536373839303132333435363738393031323322123132333435363738393031323334353637383930313233320044726f6e65204944207465737420666c696768742d2d2d420410270000f0d8ffff010000d007d00712f907d51cac0100520046494e38376173747264676531326b3800000000ac0100
```

>@dakejahl I was having the same issues as you... I added the Fix https://github.com/opendroneid/wireshark-dissector/pull/14 by NYGTEK (thanks @NYGTEK) to the wireshark dissector and I was able to see the OPENDRONEID information in my packets.

I pulled the latest but the issue is that I don't even make it this far in the code, it errors and returns due to the buffer length being too small
https://github.com/opendroneid/wireshark-dissector/blob/9e532012de4635c2103334e4f0c75293337324b3/opendroneid-dissector.lua#L562-L567

I've updated to the latest of everything, I'm going to try on Windows now instead.

**Comment by dakejahl** [comment]
Seems like it's an issue with the [transmitter-linux](https://github.com/opendroneid/transmitter-linux) example. A friend of mine Gabe Rivolta provided me with a pcap with 10 seconds of BT5 packets and I am able to successfully display it.

@gabrielcox I'm trying to compare my capture to his and the only thing that stands out to me is the coding (mine is S=2). Do you think that could have something to do with it? I can provide you with both pcap files if you wanted to look and see if you can spot the culprit. What device/software are you using as the bluetooth transmitter?

**Comment by dakejahl** [comment]
![Screenshot from 2024-01-12 17-52-53](https://github.com/opendroneid/wireshark-dissector/assets/37091262/72d6475a-9ce9-47a2-bc4f-1b3c8145134a)

**Comment by gabrielcox** [comment]
@dakejahl I don't really see how S=2 would cause this problem.  The standard requires S=8 (more EC data resulting in 125kbps and longer range) where S=2 uses less EC data providing a data rate of 500kbps (yet shorter range).  That said, the Pointer Frame->Data Frame association still exists, so although it may not be RID compliant, there's nothing preventing S=2 from a Bluetooth perspective.  What I'm seeing here is that Wireshark doesn't appear to be following the pointer frames to the data channel (apparently channel 1 in the screenshot above) to pick up the actual data frames (at 3120usecs later).  It's the data frames that will be decoded by the opendroneid dissector (it doesn't process the pointer frames -- that needs to be done by wireshark).  So there could be something in the transmitter app as you said in your final note, or there's something in the wireshark config causing it to not switch over to the data channel referenced by the pointer frame.  One thing I noticed is that you're totally filling up the frame with 230 bytes of payload.  Have you tried a smaller payload and attempting a capture with "follow devices on LE Coded Phy" turned on?

**Comment by dakejahl** [comment]
> Have you tried a smaller payload and attempting a capture with "follow devices on LE Coded Phy" turned on?

I tried this today with no luck. I also tested transmitting with my desktop and I was able to receieve/decode single messages. The desktop is transmitting on coded phy with S=8 but returns a "memory exceeded error" from `send_cmd()` when I try using message packs. Seems like only certain hardware is capable of transmitting with these requirements. FWIW the card on this desktop is BT 5.2 and the other card on the Jetson is 5.1. I ordered a newer card with 5.4 support so we'll see how that one does..

**Comment by gabrielcox** [comment]
Ok, FWIW, the requirements only come from version 5.0 of the BT standard.  So if there are any specific new features in later versions, it shouldn't be using them.

**Comment by dakejahl** [comment]
Getting a little off topic here but I think it's worth sharing in case someone else is looking into this: 

From what I've read up until 5.4 the coding scheme is chosen at the discretion of the BT controller depending on the data rate and packet size. BT 5.4 spec adds a V2 of  **LE Set Extended Advertising Parameters** command which allows the user to specify the coding scheme explicitly. 

Page 42 
https://www.bluetooth.com/wp-content/uploads/2023/02/2301_5.4_Tech_Overview_FINAL.pdf
![image](https://github.com/opendroneid/wireshark-dissector/assets/37091262/929805c0-9f09-4ae0-b584-caf5a2b45115)

There is another issue in the transmitter-linux repo which discusses this. I also tried using the "LE Set Default PHY" and "LE Set PHY" commands but had the same result as the OP (no worky). 
https://github.com/opendroneid/transmitter-linux/issues/5
