### ISSUE TITLE
Location: vertical speed is decoded as uint8, but should be int8

### ISSUE THREAD

**Issue by wico-kolmas** [opendroneid/wireshark-dissector#17]
In the Location/Vector message, vertical speed is decoded as uint8, but should be int8 because it can be positive (up) or negative (down)

Currently:
`odid_loc_vspeed = ProtoField.uint8("OpenDroneID.loc_vspeed", "Vert Speed", base.DEC)`

Should be:
`odid_loc_vspeed = ProtoField.int8("OpenDroneID.loc_vspeed", "Vert Speed", base.DEC)`

**Comment by gabrielcox** [comment]
Good Catch!  Thank you for spotting this bug.  It is now fixed in the latest check-in.
