### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by Shinobi-9T3** [opendroneid/wireshark-dissector#2]
Hi, I'm having an issue with the lua plug-in. I keep getting the error "Range is out of bounds". Has anyone else had this problem or does anyone know what it means? Thanks.

**Comment by gabrielcox** [comment]
Can you provide a screen shot and export a sample .pcap?

**Comment by gabrielcox** [comment]
@Shinobi-9T3 Also, I have made fixes in the last couple of check-ins, do you have the latest commit checked out?

**Comment by Shinobi-9T3** [comment]
![lua error](https://user-images.githubusercontent.com/83051702/146935983-951ea35e-fe6b-456d-a564-2b5e9149f285.PNG)

This is the error I receive from wireshark.  I uninstalled wireshark and reinstalled it as well as the odid plug-in last night.

**Comment by gabrielcox** [comment]
@Shinobi-9T3 , this is helpful but I would also need at least that 1 packet in a .pcap to debug and handle this condition.  It looks like that packet is actually malformed at the 802.11 level.  I suspect one of the length counters doesn't actually match the actual length.
In Wireshark, if you do the following:
1. Select packet as you have above.
2. Click "File->Export Specified Packets"
3. Choose "Selected Packets only" in the dialog.
4. Save the file as a .pcap.

Then attach the .pcap to your reply to this message.

I doubt I can fix the malformed packet issue, but I may be able to make the lua code detect and handle it better.

Thanks.

**Comment by Shinobi-9T3** [comment]
Thank you so much. Github apparently doesn't support pc
[malformed_ODID - Copy.zip](https://github.com/opendroneid/wireshark-dissector/files/7758292/malformed_ODID.-.Copy.zip)
ap files as attachments, which is surprising, so I'm attaching it as a .zip . Please let me know if this will work .

**Comment by gabrielcox** [comment]
> Thank you so much. Github apparently doesn't support pc [malformed_ODID - Copy.zip](https://github.com/opendroneid/wireshark-dissector/files/7758292/malformed_ODID.-.Copy.zip) ap files as attachments, which is surprising, so I'm attaching it as a .zip . Please let me know if this will work .

Yes, this came through find.  I'll begin worki

**Comment by gabrielcox** [comment]
@Shinobi-9T3, 
I changed the code to handle this type of frame and prevent the overrun (in the Lua code).  It is now checked into the main.  A "git pull" should show the Lua error message go away.  This specific frame is not an ODID frame -- was it expected to be one?  If it's now working to your satisfaction, please close this issue.

Thank you for finding this error handling case. :-)
--Gabriel.

**Comment by Shinobi-9T3** [comment]
Gabrielcox, I apologize for how long it's taken me too respond. The holidays have had me very busy. I appreciate you taking the time to acknowledge and work on my issue. I think I'm doing something wrong though. I don't know how to implement the core library into the android receiver example. I was able to compile the source and  export the receiver apk to my phone, but it doesn't recognize  any broadcasts(I've used my drone and a few friends drones to test it). I think that may be where the problem is with my dissector issue.  Does the wireshark dissector depend on the core c library? I'm a student in the IT field and I'm more than willing to admit that I'm wet behind the ears and definitely a "n00b". Any help you can give me is appreciated. Thank you.

**Comment by gabrielcox** [comment]
No, wireshark is working fine and doesn’t depend on anything other than the Lua code (1 file) to dissect opendroneid packets.  The fact that the errors came up was proof that the dissector was running.  It just didn’t like handling that particular packet.

Do you actually have a device sending open droneid packets?   If so, you can send the capture of that device’s packet.

if you’re wanting to create something that sends opendroneid packets, the easiest thing to start with might be an esp32.

**Comment by friissoren** [comment]
> I don't know how to implement the core library into the android receiver example
This is not necessary. The Android receiver example already contains all the code that is needed.
The core-c project is primarily meant as a help for people who implement (typically embedded) transmitters (and receivers, although I think that will be less common).

> I've used my drone and a few friends drones to test it.
Those drones probably doesn't broadcast any drone ID signals yet. The laws that dictate you have to broadcast drone ID signals are not yet mandating you to do so. If I recall correctly, in the US it will be towards the end of 2022 and in Europe in the beginning of 2023. I therefore expect that most drones currently on the market do not yet broadcast ID signals. Firmware updates will at some point allow some of those to do that later on. Some might need additional HW added.

If you want to setup your own transmitter for testing, some examples are available:
https://github.com/opendroneid/opendroneid-core-c#linux
