### ISSUE TITLE
Opendroneid-dissector.lua file  debug info

### ISSUE THREAD

**Issue by CYuSir** [opendroneid/wireshark-dissector#23]
can you help me. Thanks
![20241202-173504](https://github.com/user-attachments/assets/cb7641bd-d2c7-4e53-be2e-4278a8f2e586)

 i get errors, its not work.
 
 frameTypeOffset: 17, frameType: 54974, frameType4=2391391958(0x8e89bed6), len=136
BT ADV_NONCONN_IND, but not SVC_DATA_TYPE
start==0
debug on
too short (34 < 58
debug on
too short (34 < 58
debug on
too short (34 < 58
debug on
frameTypeOffset: 17, frameType: 54974, frameType4=2391391958(0x8e89bed6), len=136
BT ADV_NONCONN_IND, but not SVC_DATA_TYPE
start==0
debug on
too short (34 < 58
debug on
too short (34 < 58
debug on
too short (34 < 58
debug on
frameTypeOffset: 17, frameType: 54974, frameType4=2391391958(0x8e89bed6), len=136
BT ADV_NONCONN_IND, but not SVC_DATA_TYPE

**Comment by gabrielcox** [comment]
I think the problem is in the 16-bit UUID.  It should be 0xFFFA.

Like this:

<img width="787" alt="image" src="https://github.com/user-attachments/assets/8bf9ed48-2fc8-4fb9-aa1a-af4444436486">

**Comment by CYuSir** [comment]
I restructured some of the application logic, get this. My device sends ble 5 LR and can only send connect flag true packet for the time being, so the Flags subtree appears. Compare it to your screenshot.
![Uploading 20241203-103227.jpg…]()

**Comment by CYuSir** [comment]
I restructured some of the application logic, get this. My device sends ble 5 LR and can only send connect flag true packet for the time being, so the Flags subtree appears. Compare it to your screenshot.
![20241203-103227](https://github.com/user-attachments/assets/ba0ffd16-c96c-4cc0-a5c6-73ab5bf91f57)

**Comment by gabrielcox** [comment]
1. One of the first lines in the Lua Script has Debug = 0, set that to 1.  Save it.
1. Click on Tools->Lua Console and keep that window open off to the side.
1. Use Ctrl+Shift+L to reload the Lua script.  
-- You should see output in the Lua Console (which should show why it's not matching to begin parsing).
1. If you don't see output in the console.wireshark, 
-- Go to Help->About->Folders
-- look at "Personal Lua Scripts", click on it, and make sure the dissector Lua script is there or in a sub-folder.

**Comment by CYuSir** [comment]
ok, thanks, i will try it

**Comment by CYuSir** [comment]
Thank you so much.
Now I can, correctly capture and parse to OpenDroneID
![20241203-131830](https://github.com/user-attachments/assets/c6f3fea1-d598-416d-b8cd-333a7cc9925f)

**Comment by CYuSir** [comment]
But，I encountered some other problems during the debugging process, and tried to modify and adjust the Opendroneid-dissector.lua file, as shown in the screenshot
![20241203-131835](https://github.com/user-attachments/assets/29a3b619-3107-4f81-9af0-63173d19ce91)
![20241203-131841](https://github.com/user-attachments/assets/5e07d67a-f646-438a-b407-d77ff90480d8)
![20241203-131845](https://github.com/user-attachments/assets/045c0a77-192f-4c36-9461-5d47ba7dcaf3)
![20241203-131850](https://github.com/user-attachments/assets/bd90d640-b14f-46fd-a5eb-8e5cc2cfea86)
The implementation of timeDelta10 and timeDelta10v functions has been slightly adjusted. 
But modified BT5_OFF_ADDER = 5 + 3 .
In the end, such modifications can be successfully captured and parsed
