### ISSUE TITLE
Dissector for Bluetooth

### ISSUE THREAD

**Issue by aravindraja93** [opendroneid/wireshark-dissector#5]
I am not able to dissect using the plugin for Bluetooth data captured using the same nordic 5280DK.

Does the dissector need to added to the relevant bluetooth dissector table in the Lua ?

![image](https://user-images.githubusercontent.com/84900769/174423446-be79b8d3-281f-4493-8d58-9ff83870190f.png)

**Comment by gabrielcox** [comment]
Does it not show up as a separate tree below? 
like this:
![image](https://user-images.githubusercontent.com/13051211/174426127-94ebcfac-7039-4073-afc4-8f180628d50e.png)
Can you send a full application screen shot?   
What does it say in the protocol column of that frame (see my screenshot, top list of frames, protocol column)
From looking at it, the data looks like it should parse.
Also, if you could send a .pcap of the individual frame, I could look at it from my end as well.

**Comment by aravindraja93** [comment]
It doesn't add a separate tree. 
[only_req_ble.zip](https://github.com/opendroneid/wireshark-dissector/files/8933564/only_req_ble.zip)
![image](https://user-images.githubusercontent.com/84900769/174438489-8858e37a-97fb-4611-a4c5-58b49c3dca4f.png)
Adding the full screenshot and the .pcap file too. 

The data looks parseable and also the OPENDRONEID shows up in the enabled protocols and available inside wtap_encap. Not able to see why it fails with Bluetooth but works with wifi

Thank you

**Comment by gabrielcox** [comment]
Ok, I'll pull this pcap into my wireshark tonight to see if I can reproduce.  

In the meantime, if you look at the Lua code, there's a debug mode at the top that you can turn on (setting =1). That should cause some console output.

**Comment by aravindraja93** [comment]
![image](https://user-images.githubusercontent.com/84900769/174524653-672e4a88-a4d4-4803-9fdb-081cc68b25e1.png)

**Comment by gabrielcox** [comment]
Ok, I pushed in a "fix".  It's not very fancy, but it checks to see if the frameTypeOffset ends up being 0 and it's 56 bytes, then it assumes it's a BT4 captures and sets the frameTypeOffset to 0x11.  Everything runs fine from there and it preserves compatibility with wi-fi (which uses the offsets as originally programmed).

**Comment by aravindraja93** [comment]
Got it. Will check with the fix.
Yes, Will create a PR.
