### ISSUE TITLE
Error Message When Using Dissector

### ISSUE THREAD

**Issue by losmurfs** [opendroneid/wireshark-dissector#8]
Lua Error: ...rk\plugins\wireshark-dissector\opendroneid-dissector.lua:437: Range is out of bounds

**Comment by gabrielcox** [comment]
@losmurfs, @dviresh93 If you see this, please export a .pcap of the individual packet on which you see the error.  I can then debug.

**Comment by thomasamelootrigitech** [comment]
I had the same issue, please find a .pcap with some packets that triggered the error attached.

[error_packets.zip](https://github.com/opendroneid/wireshark-dissector/files/13658631/error_packets.zip)

**Comment by gabrielcox** [comment]
@thomasamelootrigitech , Thank you for the info.  When sniffing raw network UDP packets, the byte where the frame offset is supposed to be is something different (likely part of the Source MAC ADDR).  I did better range checking to detect this in the latest version.  So if you pull the latest updates, it should be resolved for this case.  There's probably even more improvements that could be made to check for the "signature" of being in the proper sniffing mode to abandon the packet earlier.
Please update, confirm resolved and close this issue as appropriate.
