### ISSUE TITLE
Wireshark BT5 Plans / Timeline?

### ISSUE THREAD

**Issue by viet-nguyen-matternet** [opendroneid/wireshark-dissector#9]
Just wondering if this tool will be updated for BT5 or not, and if so, what timeline does that look like

**Comment by sandeshworld** [comment]
Seconding this. Anyone working on support for BT5 already?

**Comment by Mf-ff99** [comment]
BT5 support would be great :)

**Comment by gabrielcox** [comment]
@viet-nguyen-matternet, @sandeshworld, @Mf-ff99.  It is done.  If you have the nRF52840 dongle with the latest sniffer installed on the dongle, the latest dissector should work.  be sure the latest nrf sniffer plugin is installed in wireshark as well.  It provides sniffing options such as "Scan and follow devices on LE Coded Phy".  This will "follow" the BT5 frames.
